#!/bin/bash

DOCKER_ARMBIAN_BASE_IMAGE=ubuntu:noble ./compile.sh KERNEL_GIT=shallow BOARD=orangepi4-lts BRANCH=edge BUILD_DESKTOP=yes BUILD_MINIMAL=no DESKTOP_ENVIRONMENT=gnome DESKTOP_ENVIRONMENT_CONFIG_NAME=config_base KERNEL_CONFIGURE=yes RELEASE=noble DESKTOP_APPGROUPS_SELECTED='' INSTALL_HEADERS=yes DOCKER_ARMBIAN_BASE_IMAGE='ubuntu:noble' CLEAN_LEVEL='make-atf,debs,images,oldcache,extra' BSPFREEZE='yes' BOARD_FIRMWARE_INSTALL="-full"
