#!/bin/bash

./compile.sh KERNEL_GIT=shallow BOARD=orangepi4-lts BRANCH=edge BUILD_DESKTOP=yes BUILD_MINIMAL=no DESKTOP_ENVIRONMENT=gnome DESKTOP_ENVIRONMENT_CONFIG_NAME=config_base KERNEL_CONFIGURE='no' DESKTOP_APPGROUPS_SELECTED='' RELEASE='noble' INSTALL_HEADERS=yes DOCKER_ARMBIAN_BASE_IMAGE='ubuntu:noble' BSPFREEZE='yes' BOARD_FIRMWARE_INSTALL="-full" kernel-patch

#./compile.sh KERNEL_GIT=shallow BOARD=orangepi4-lts BRANCH=edge BUILD_DESKTOP=yes BUILD_MINIMAL=no DESKTOP_ENVIRONMENT=gnome DESKTOP_ENVIRONMENT_CONFIG_NAME=config_base KERNEL_CONFIGURE='no' DESKTOP_APPGROUPS_SELECTED='' RELEASE='noble' INSTALL_HEADERS=yes DOCKER_ARMBIAN_BASE_IMAGE='ubuntu:noble' BSPFREEZE='yes' BOARD_FIRMWARE_INSTALL="-full" KERNELBRANCH=tag:'v6.12.3' KERNEL_MAJOR_MINOR='6.12.3' KERNELPATCHDIR='archive/rockchip64-6.12' kernel

#./compile.sh KERNEL_GIT=shallow BOARD=orangepi4-lts BRANCH=edge BUILD_DESKTOP=yes BUILD_MINIMAL=no DESKTOP_ENVIRONMENT=kde-plasma EXPERT=yes BETA=yes DESKTOP_ENVIRONMENT_CONFIG_NAME=config_base KERNEL_CONFIGURE=no DESKTOP_APPGROUPS_SELECTED='' RELEASE='trixie' INSTALL_HEADERS=yes DOCKER_ARMBIAN_BASE_IMAGE='debian:trixie' BSPFREEZE='yes' BOARD_FIRMWARE_INSTALL="-full" $1

#./compile.sh KERNEL_GIT=shallow BOARD=orangepi4-lts BRANCH=edge BUILD_DESKTOP=yes BUILD_MINIMAL=no DESKTOP_ENVIRONMENT=kde-plasma EXPERT=yes BETA=yes DESKTOP_ENVIRONMENT_CONFIG_NAME=config_base KERNEL_CONFIGURE=no DESKTOP_APPGROUPS_SELECTED='' RELEASE='noble' INSTALL_HEADERS=yes DOCKER_ARMBIAN_BASE_IMAGE='ubuntu:noble' BSPFREEZE='yes' BOARD_FIRMWARE_INSTALL="-full" $1

#./compile.sh KERNEL_GIT=shallow BOARD=orangepi4-lts BRANCH=edge BUILD_DESKTOP=no BUILD_MINIMAL=no KERNEL_CONFIGURE=no RELEASE='trixie' INSTALL_HEADERS=yes DOCKER_ARMBIAN_BASE_IMAGE='ubuntu:noble' BSPFREEZE='yes' BOARD_FIRMWARE_INSTALL="-full" $1

